<?php

class WP_GET_GITHUB_REPOS extends WP_Widget {

	// Constructor to Create Widget
	function __construct() {
		parent::__construct(
			'my_github_repos',
			__('My Github Repos', 'wpggr_domain'),
			array('description' => __('A widget to display your Guthub repos in a widget', 'wpggr_domain'))
		);
	}


	// Create Widget Front End Display
	public function widget($args, $instance) {

	}

	// Create Widget Backend Form
	public function form( $instance ) {
		return parent::form( $instance ); // TODO: Change the autogenerated stub
	}

	// Create Widget Value Update Method
	public function update( $new_instance, $old_instance ) {
		return parent::update( $new_instance, $old_instance ); // TODO: Change the autogenerated stub
	}
}